image: $CI_REGISTRY/hdtn-v4/hdtn/debian-base

# Configure the pipeline stages
stages:
  - build
  - test
  - static-analysis

# Set global environment variables
variables:
  HDTN_SOURCE_ROOT: "$PWD"

# Set the pipleline to run for merge request events only
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# Build HDTN with the default configuration
# Don't save any artifacts, just confirm the build
build:
  stage: build
  tags:
  - docker
  - linux-x86
  script:
    - mkdir build
    - cmake -S . -B build
    - make -C build/ -j8

# Build HDTN with the GUI enabled
# Save the output to use for testing
build-with-gui:
  stage: build
  tags:
  - docker
  - linux
  script:
    - mkdir external
    - cp -r /home/civetweb/include external/include
    - mkdir external/lib
    - cp /home/civetweb/libcivetweb.a external/lib
    - mkdir build
    - cmake -S . -B build -D USE_WEB_INTERFACE:BOOL=ON
    - make -C build/ -j8
  artifacts:
    paths:
      - build

# Run unit tests and generate a test report
unit-test:
  stage: test
  tags:
  - docker
  - linux-x86
  script:
    - ./build/tests/unit_tests/unit-tests --log_format=JUNIT --log_sink=report.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml

# Start coverity Static Analysis Scanning 
static-analysis:
  stage: static-analysis
  tags:
  - cov-analysis
  script:
    - export PATH=/home/hdtn/cov-analysis-linux64-2022.6.1/bin:$PATH
    - cd build
    - make clean
    - cov-build --dir idir make -j8
    - cov-analyze --dir idir --all --enable-constraint-fpp --enable-fnptr --enable-virtual --strip-path $HDTN_SOURCE_ROOT
    - cov-commit-defects --dir idir --url  https://10.54.31.120:8443 --stream HDTN-master --auth-key-file /home/hdtn/auth.key
      
