image: $CI_REGISTRY/hdtn-v4/hdtn/debian-base

# Configure the pipeline stages
stages:
  - build
  - test

# Set global environment variables
variables:
  HDTN_SOURCE_ROOT: "$PWD"

# Set the pipleline to run for merge request events only
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# Build HDTN with the default configuration
# Don't save any artifacts, just confirm the build
build:
  stage: build
  tags:
  - docker
  - linux
  script:
    - mkdir build
    - cmake -S . -B build
    - make -C build/ -j16

# Build HDTN with the GUI enabled
# Save the output to use for testing
build-with-gui:
  stage: build
  tags:
  - docker
  - linux
  script:
    - mkdir external
    - cp -r /home/civetweb/include external/include
    - mkdir external/lib
    - cp /home/civetweb/libcivetweb.a external/lib
    - mkdir build
    - cmake -S . -B build -D USE_WEB_INTERFACE:BOOL=ON
    - make -C build/ -j16
  artifacts:
    paths:
      - build

# Run unit tests and generate a test report
unit-test:
  stage: test
  tags:
  - docker
  - linux
  script:
    - ./build/tests/unit_tests/unit-tests --log_format=JUNIT --log_sink=report.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
