version: '3.7'
services:
    alpha:
      build: ../oracle_linux/
      container_name: hdtn_sender
      hostname: hdtn_sender
      image: hdtn
      tty: true
      extra_hosts: 
      - "hdtn-1:10.0.2.1"
    bravo:
      build: ../oracle_linux/
      container_name: hdtn_receiver
      hostname: hdtn_receiver
      image: hdtn
      tty: true
      extra_hosts:
      - "hdtn-2:10.0.2.2"


