name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-x64-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Test Start
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake ..
          make -j8

          # - name: Unit Tests
          #run: |
          #export HDTN_SOURCE_ROOT=$PWD
          #cd $HDTN_SOURCE_ROOT
          #cd build
          #./tests/unit_tests/unit-tests

      # - name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  coverity-test:
    runs-on:  [self-hosted, ubuntu, x64]
    
    steps:
      - uses: actions/checkout@v3
       
      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8
          sudo make install

      - name: Coverity Scan
        run: |
          export PATH=/home/hdtn/cov-analysis-linux64-2022.6.1/bin:$PATH
          cd build
          make clean
          cov-build --dir idir make -j8
          cov-analyze --dir idir --all --enable-constraint-fpp --enable-fnptr --enable-virtual --strip-path $HDTN_SOURCE_ROOT
          cov-commit-defects --dir idir --url  https://10.54.31.120:8443 --stream HDTN-master --auth-key-file /home/hdtn/auth.key
