name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-x64-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      # - name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests
      
  oracle-x64-test:
    runs-on: [self-hosted, oracle, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo yum install cmake
          sudo yum update
          sudo dnf install epel-release
          sudo yum install boost-devel
          sudo yum install zeromq
          sudo yum install zeromq-devel

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -D ENABLE_OPENSSL_SUPPORT:BOOL=OFF -DBOOST_INCLUDEDIR=/usr/include/boost169 .. -DBOOST_LIBRARYDIR=/usr/lib64/boost169 ..
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  debian-x64-test:
    runs-on: [self-hosted, debian, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  ubuntu-arm-test:
    runs-on: [self-hosted, ubuntu, ARM64]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD 
          cd $HDTN_SOURCE_ROOT 
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=Release -D LTP_RNG_USE_RDSEED:BOOL=OFF -D USE_X86_HARDWARE_ACCELERATION:BOOL=OFF -D Boost_USE_STATIC_LIBS:UNINITIALIZED=OFF -D CMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG -fPIC" ..
          cd $HDTN_SOURCE_ROOT/common/util/  
          sed -i '2 s/^/#/' CMakeLists.txt 
          cd $HDTN_SOURCE_ROOT/tests/unit_tests
          sed -i '20 s/^/#/' CMakeLists.txt
          cd $HDTN_SOURCE_ROOT/build
          cmake -DCMAKE_BUILD_TYPE=Release .. 
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  debian-arm-test:
    runs-on: [self-hosted, debian, ARM64]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=Release -D LTP_RNG_USE_RDSEED:BOOL=OFF -D USE_X86_HARDWARE_ACCELERATION:BOOL=OFF -D Boost_USE_STATIC_LIBS:UNINITIALIZED=OFF -D CMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG -fPIC" ..
          cd $HDTN_SOURCE_ROOT/common/util/
          sed -i '2 s/^/#/' CMakeLists.txt 
          cd $HDTN_SOURCE_ROOT/tests/unit_tests
          sed -i '20 s/^/#/' CMakeLists.txt
          cd $HDTN_SOURCE_ROOT/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests