name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Test Start
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="

      - name: Install CMake
        run: |
          echo "============================================================="
          echo "Install CMake"
          echo "============================================================="
          sudo apt-get install cmake

      - name: Setup build-essential
        run: |
          echo "============================================================="
          echo "Setup build-essential"
          echo "============================================================="
          sudo apt-get install build-essential

      - name: Install Boost
        run: |
          echo "============================================================="
          echo "Install Boost"
          echo "============================================================="
          sudo apt-get install libboost-dev libboost-all-dev

      - name: Install ZeroMQ
        run: |
          echo "============================================================="
          echo "Install ZeroMQ"
          echo "============================================================="
          sudo apt-get install libzmq3-dev python3-zmq

      - name: Install OpenSSL
        run: |
          echo "============================================================="
          echo "Install OpenSSL"
          echo "============================================================="
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8
          sudo make install

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          cd build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests
